module.exports = {
  pets: [
    { type: "perro", name: "coraje", owner: "oscar", updated_at: new Date(), created_at: new Date()},
    { type: "perro", name: "coraje", owner: "oscar", updated_at: new Date(), created_at: new Date() },
    { type: "perro", name: "coraje", owner: "oscar", updated_at: new Date(), created_at: new Date() },
    { type: "perro", name: "coraje", owner: "oscar", updated_at: new Date(), created_at: new Date() },
    { type: "perro", name: "coraje", owner: "oscar", updated_at: new Date(), created_at: new Date() },
    { type: "perro", name: "coraje", owner: "oscar", updated_at: new Date(), created_at: new Date() },
    { type: "perro", name: "coraje", owner: "oscar", updated_at: new Date(), created_at: new Date() },
    { type: "perro", name: "coraje", owner: "oscar", updated_at: new Date(), created_at: new Date() },
    { type: "perro", name: "coraje", owner: "manhuel", updated_at: new Date(), created_at: new Date() },
  ],
  veterinarians: [
    {
      identification: "128515355485",
      name: "coraje",
      lastname: "oscar",
      country: "España",
      updated_at: new Date(),
      created_at: new Date(),
    },
    {
      identification: "1285153556145",
      name: "coraje",
      lastname: "jon",
      country: "Colombia",
      updated_at: new Date(),
      created_at: new Date(),
    },
    {
      identification: "1285153558454",
      name: "coraje",
      lastname: "manhuel",
      country: "España",
      updated_at: new Date(),
      created_at: new Date(),
    },
  ],
  owners: [
    {
      identification: "78",
      name: "coraje",
      lastname: "oscar",
      country: "España",
      updated_at: new Date(),
      created_at: new Date(),
    },
    {
      identification: "89",
      name: "coraje",
      lastname: "amel",
      country: "España",
      updated_at: new Date(),
      created_at: new Date(),
    },
    {
      identification: "45",
      name: "coraje",
      lastname: "manhuel",
      country: "España",
      updated_at: new Date(),
      created_at: new Date(),
    },
  ],
  consults: [
    {
      mascota: 0,
      veterinarian: 0,
      updated_at: new Date(),
      created_at: new Date(),
      log: "",
      diagnosis: "",
    },
  ],
};
